"""added is_active column in todo table

Revision ID: 42367c36b8bd
Revises: cb6746312aad
Create Date: 2024-09-19 16:47:23.651568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42367c36b8bd'
down_revision: Union[str, None] = 'cb6746312aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'is_active')
    # ### end Alembic commands ###
